services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      # TODO:本番APIのURL（仮）
      - BASE_URL=https://family-ops-api.onrender.com
    command: node .output/server/index.mjs
    ports:
      # 必要に応じて外部公開ポートを調整
      - "3001:3000"


