services:
  api:
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - ALLOWED_ORIGINS=https://family-ops-client.onrender.com
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - BASE_URL=https://family-ops-api.onrender.com
    command: node .output/server/index.mjs
    ports:
      # 必要に応じて外部公開ポートを調整
      - "3001:3000"


